
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
MetaModelOptions <- R6::R6Class(
    "MetaModelOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            yi = NULL,
            vi = NULL,
            studylabels = NULL,
            method = "REML", ...) {

            super$initialize(
                package='MetaModel',
                name='MetaModel',
                requiresData=TRUE,
                ...)
        
            private$..yi <- jmvcore::OptionVariable$new(
                "yi",
                yi)
            private$..vi <- jmvcore::OptionVariable$new(
                "vi",
                vi)
            private$..studylabels <- jmvcore::OptionVariable$new(
                "studylabels",
                studylabels)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "DL",
                    "HE",
                    "HS",
                    "SJ",
                    "ML",
                    "REML",
                    "EB",
                    "PM",
                    "FE"),
                default="REML")
        
            self$.addOption(private$..yi)
            self$.addOption(private$..vi)
            self$.addOption(private$..studylabels)
            self$.addOption(private$..method)
        }),
    active = list(
        yi = function() private$..yi$value,
        vi = function() private$..vi$value,
        studylabels = function() private$..studylabels$value,
        method = function() private$..method$value),
    private = list(
        ..yi = NA,
        ..vi = NA,
        ..studylabels = NA,
        ..method = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
MetaModelResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$..text,
        plot = function() private$..plot),
    private = list(
        ..text = NA,
        ..plot = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Meta-Analysis")
            private$..text <- jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Meta-Analysis")
            private$..plot <- jmvcore::Image$new(
                options=options,
                name="plot",
                title="Forest Plot",
                width=600,
                height=450,
                renderFun=".plot")
            self$add(private$..text)
            self$add(private$..plot)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
MetaModelBase <- R6::R6Class(
    "MetaModelBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MetaModel',
                name = 'MetaModel',
                version = c(1,0,0),
                options = options,
                results = MetaModelResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Meta-Analysis
#'
#' 
#' @param data .
#' @param yi .
#' @param vi .
#' @param studylabels .
#' @param method .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
MetaModel <- function(
    data,
    yi,
    vi,
    studylabels,
    method = "REML") {

    options <- MetaModelOptions$new(
        yi = yi,
        vi = vi,
        studylabels = studylabels,
        method = method)

    results <- MetaModelResults$new(
        options = options)

    analysis <- MetaModelClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
