
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
metamdmsOptions <- R6::R6Class(
    "metamdmsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            n1i = NULL,
            m1i = NULL,
            sd1i = NULL,
            n2i = NULL,
            m2i = NULL,
            sd2i = NULL,
            slab = NULL,
            moderator = NULL,
            includemods = FALSE,
            methodmetamdms = "REML",
            mdmsmeasure = "SMD",
            level = 95,
            addcred = FALSE,
            addfit = TRUE,
            showweights = FALSE,
            fsntype = "Rosenthal",
            yaxis = "sei", ...) {

            super$initialize(
                package='MetaModel',
                name='metamdms',
                requiresData=TRUE,
                ...)
        
            private$..n1i <- jmvcore::OptionVariable$new(
                "n1i",
                n1i)
            private$..m1i <- jmvcore::OptionVariable$new(
                "m1i",
                m1i)
            private$..sd1i <- jmvcore::OptionVariable$new(
                "sd1i",
                sd1i)
            private$..n2i <- jmvcore::OptionVariable$new(
                "n2i",
                n2i)
            private$..m2i <- jmvcore::OptionVariable$new(
                "m2i",
                m2i)
            private$..sd2i <- jmvcore::OptionVariable$new(
                "sd2i",
                sd2i)
            private$..slab <- jmvcore::OptionVariable$new(
                "slab",
                slab)
            private$..moderator <- jmvcore::OptionVariable$new(
                "moderator",
                moderator)
            private$..includemods <- jmvcore::OptionBool$new(
                "includemods",
                includemods,
                default=FALSE)
            private$..methodmetamdms <- jmvcore::OptionList$new(
                "methodmetamdms",
                methodmetamdms,
                options=list(
                    "DL",
                    "HE",
                    "HS",
                    "SJ",
                    "ML",
                    "REML",
                    "EB",
                    "FE"),
                default="REML")
            private$..mdmsmeasure <- jmvcore::OptionList$new(
                "mdmsmeasure",
                mdmsmeasure,
                options=list(
                    "MD",
                    "SMD",
                    "SMDH",
                    "ROM"),
                default="SMD")
            private$..level <- jmvcore::OptionNumber$new(
                "level",
                level,
                min=50,
                max=99.9,
                default=95)
            private$..addcred <- jmvcore::OptionBool$new(
                "addcred",
                addcred,
                default=FALSE)
            private$..addfit <- jmvcore::OptionBool$new(
                "addfit",
                addfit,
                default=TRUE)
            private$..showweights <- jmvcore::OptionBool$new(
                "showweights",
                showweights,
                default=FALSE)
            private$..fsntype <- jmvcore::OptionList$new(
                "fsntype",
                fsntype,
                options=list(
                    "Rosenthal",
                    "Orwin",
                    "Rosenberg"),
                default="Rosenthal")
            private$..yaxis <- jmvcore::OptionList$new(
                "yaxis",
                yaxis,
                options=list(
                    "sei",
                    "seinv",
                    "vi",
                    "vinv",
                    "ni",
                    "ninv",
                    "sqrtni",
                    "sqrtninv",
                    "lni"),
                default="sei")
        
            self$.addOption(private$..n1i)
            self$.addOption(private$..m1i)
            self$.addOption(private$..sd1i)
            self$.addOption(private$..n2i)
            self$.addOption(private$..m2i)
            self$.addOption(private$..sd2i)
            self$.addOption(private$..slab)
            self$.addOption(private$..moderator)
            self$.addOption(private$..includemods)
            self$.addOption(private$..methodmetamdms)
            self$.addOption(private$..mdmsmeasure)
            self$.addOption(private$..level)
            self$.addOption(private$..addcred)
            self$.addOption(private$..addfit)
            self$.addOption(private$..showweights)
            self$.addOption(private$..fsntype)
            self$.addOption(private$..yaxis)
        }),
    active = list(
        n1i = function() private$..n1i$value,
        m1i = function() private$..m1i$value,
        sd1i = function() private$..sd1i$value,
        n2i = function() private$..n2i$value,
        m2i = function() private$..m2i$value,
        sd2i = function() private$..sd2i$value,
        slab = function() private$..slab$value,
        moderator = function() private$..moderator$value,
        includemods = function() private$..includemods$value,
        methodmetamdms = function() private$..methodmetamdms$value,
        mdmsmeasure = function() private$..mdmsmeasure$value,
        level = function() private$..level$value,
        addcred = function() private$..addcred$value,
        addfit = function() private$..addfit$value,
        showweights = function() private$..showweights$value,
        fsntype = function() private$..fsntype$value,
        yaxis = function() private$..yaxis$value),
    private = list(
        ..n1i = NA,
        ..m1i = NA,
        ..sd1i = NA,
        ..n2i = NA,
        ..m2i = NA,
        ..sd2i = NA,
        ..slab = NA,
        ..moderator = NA,
        ..includemods = NA,
        ..methodmetamdms = NA,
        ..mdmsmeasure = NA,
        ..level = NA,
        ..addcred = NA,
        ..addfit = NA,
        ..showweights = NA,
        ..fsntype = NA,
        ..yaxis = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
metamdmsResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$..text,
        plot = function() private$..plot,
        placeholder = function() private$..placeholder,
        fsn = function() private$..fsn,
        rank = function() private$..rank,
        reg = function() private$..reg,
        funplot = function() private$..funplot),
    private = list(
        ..text = NA,
        ..plot = NA,
        ..placeholder = NA,
        ..fsn = NA,
        ..rank = NA,
        ..reg = NA,
        ..funplot = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Meta-Analysis")
            private$..text <- jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Mean Differences")
            private$..plot <- jmvcore::Image$new(
                options=options,
                name="plot",
                title="Forest Plot",
                width=600,
                height=450,
                renderFun=".plot")
            private$..placeholder <- jmvcore::Preformatted$new(
                options=options,
                name="placeholder",
                title="Publication Bias Assessment")
            private$..fsn <- jmvcore::Preformatted$new(
                options=options,
                name="fsn",
                title="Fail-Safe N Analysis")
            private$..rank <- jmvcore::Preformatted$new(
                options=options,
                name="rank",
                title="Rank Correlation Test for Funnel Plot Asymmetry")
            private$..reg <- jmvcore::Preformatted$new(
                options=options,
                name="reg",
                title="Regression Test for Funnel Plot Asymmetry")
            private$..funplot <- jmvcore::Image$new(
                options=options,
                name="funplot",
                title="Funnel Plot",
                width=600,
                height=450,
                renderFun=".funplot")
            self$add(private$..text)
            self$add(private$..plot)
            self$add(private$..placeholder)
            self$add(private$..fsn)
            self$add(private$..rank)
            self$add(private$..reg)
            self$add(private$..funplot)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
metamdmsBase <- R6::R6Class(
    "metamdmsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MetaModel',
                name = 'metamdms',
                version = c(1,0,0),
                options = options,
                results = metamdmsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Mean Differences (n, M, SD)
#'
#' 
#' @param data .
#' @param n1i .
#' @param m1i .
#' @param sd1i .
#' @param n2i .
#' @param m2i .
#' @param sd2i .
#' @param slab .
#' @param moderator .
#' @param includemods .
#' @param methodmetamdms .
#' @param mdmsmeasure .
#' @param level .
#' @param addcred .
#' @param addfit .
#' @param showweights .
#' @param fsntype .
#' @param yaxis .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$placeholder} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$fsn} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$rank} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$reg} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$funplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
metamdms <- function(
    data,
    n1i,
    m1i,
    sd1i,
    n2i,
    m2i,
    sd2i,
    slab,
    moderator,
    includemods = FALSE,
    methodmetamdms = "REML",
    mdmsmeasure = "SMD",
    level = 95,
    addcred = FALSE,
    addfit = TRUE,
    showweights = FALSE,
    fsntype = "Rosenthal",
    yaxis = "sei") {

    options <- metamdmsOptions$new(
        n1i = n1i,
        m1i = m1i,
        sd1i = sd1i,
        n2i = n2i,
        m2i = m2i,
        sd2i = sd2i,
        slab = slab,
        moderator = moderator,
        includemods = includemods,
        methodmetamdms = methodmetamdms,
        mdmsmeasure = mdmsmeasure,
        level = level,
        addcred = addcred,
        addfit = addfit,
        showweights = showweights,
        fsntype = fsntype,
        yaxis = yaxis)

    results <- metamdmsResults$new(
        options = options)

    analysis <- metamdmsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
