
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
MetaCorrOptions <- R6::R6Class(
    "MetaCorrOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            ri = NULL,
            ni = NULL,
            methodmetacor = "REML",
            cormeasure = "ZCOR", ...) {

            super$initialize(
                package='MetaModel',
                name='MetaCorr',
                requiresData=TRUE,
                ...)
        
            private$..ri <- jmvcore::OptionVariable$new(
                "ri",
                ri)
            private$..ni <- jmvcore::OptionVariable$new(
                "ni",
                ni)
            private$..methodmetacor <- jmvcore::OptionList$new(
                "methodmetacor",
                methodmetacor,
                options=list(
                    "DL",
                    "HE",
                    "HS",
                    "SJ",
                    "ML",
                    "REML",
                    "EB",
                    "PM",
                    "FE"),
                default="REML")
            private$..cormeasure <- jmvcore::OptionList$new(
                "cormeasure",
                cormeasure,
                options=list(
                    "COR",
                    "UCOR",
                    "ZCOR"),
                default="ZCOR")
        
            self$.addOption(private$..ri)
            self$.addOption(private$..ni)
            self$.addOption(private$..methodmetacor)
            self$.addOption(private$..cormeasure)
        }),
    active = list(
        ri = function() private$..ri$value,
        ni = function() private$..ni$value,
        methodmetacor = function() private$..methodmetacor$value,
        cormeasure = function() private$..cormeasure$value),
    private = list(
        ..ri = NA,
        ..ni = NA,
        ..methodmetacor = NA,
        ..cormeasure = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
MetaCorrResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$..text),
    private = list(
        ..text = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Meta-analysis of Correlation Coefficients")
            private$..text <- jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Meta-analysis of Correlation Coefficients")
            self$add(private$..text)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
MetaCorrBase <- R6::R6Class(
    "MetaCorrBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MetaModel',
                name = 'MetaCorr',
                version = c(1,0,0),
                options = options,
                results = MetaCorrResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Meta-analysis of Correlation Coefficients
#'
#' 
#' @param data .
#' @param ri .
#' @param ni .
#' @param methodmetacor .
#' @param cormeasure .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
MetaCorr <- function(
    data,
    ri,
    ni,
    methodmetacor = "REML",
    cormeasure = "ZCOR") {

    options <- MetaCorrOptions$new(
        ri = ri,
        ni = ni,
        methodmetacor = methodmetacor,
        cormeasure = cormeasure)

    results <- MetaCorrResults$new(
        options = options)

    analysis <- MetaCorrClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
