
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
MetaCorrOptions <- R6::R6Class(
    "MetaCorrOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rcor = NULL,
            samplesize = NULL,
            methodmetacor = "REML",
            cormeasure = "ZCOR",
            fsntype = "Rosenthal",
            yaxis = "sei", ...) {

            super$initialize(
                package='MetaModel',
                name='MetaCorr',
                requiresData=TRUE,
                ...)
        
            private$..rcor <- jmvcore::OptionVariable$new(
                "rcor",
                rcor)
            private$..samplesize <- jmvcore::OptionVariable$new(
                "samplesize",
                samplesize)
            private$..methodmetacor <- jmvcore::OptionList$new(
                "methodmetacor",
                methodmetacor,
                options=list(
                    "DL",
                    "HE",
                    "HS",
                    "SJ",
                    "ML",
                    "REML",
                    "EB",
                    "PM",
                    "FE"),
                default="REML")
            private$..cormeasure <- jmvcore::OptionList$new(
                "cormeasure",
                cormeasure,
                options=list(
                    "COR",
                    "UCOR",
                    "ZCOR"),
                default="ZCOR")
            private$..fsntype <- jmvcore::OptionList$new(
                "fsntype",
                fsntype,
                options=list(
                    "Rosenthal",
                    "Orwin",
                    "Rosenberg"),
                default="Rosenthal")
            private$..yaxis <- jmvcore::OptionList$new(
                "yaxis",
                yaxis,
                options=list(
                    "sei",
                    "seinv",
                    "vi",
                    "vinv",
                    "ni",
                    "ninv",
                    "sqrtni",
                    "sqrtninv",
                    "lni"),
                default="sei")
        
            self$.addOption(private$..rcor)
            self$.addOption(private$..samplesize)
            self$.addOption(private$..methodmetacor)
            self$.addOption(private$..cormeasure)
            self$.addOption(private$..fsntype)
            self$.addOption(private$..yaxis)
        }),
    active = list(
        rcor = function() private$..rcor$value,
        samplesize = function() private$..samplesize$value,
        methodmetacor = function() private$..methodmetacor$value,
        cormeasure = function() private$..cormeasure$value,
        fsntype = function() private$..fsntype$value,
        yaxis = function() private$..yaxis$value),
    private = list(
        ..rcor = NA,
        ..samplesize = NA,
        ..methodmetacor = NA,
        ..cormeasure = NA,
        ..fsntype = NA,
        ..yaxis = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
MetaCorrResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$..text,
        plot = function() private$..plot,
        placeholder = function() private$..placeholder,
        fsn = function() private$..fsn,
        rank = function() private$..rank,
        reg = function() private$..reg,
        funplot = function() private$..funplot),
    private = list(
        ..text = NA,
        ..plot = NA,
        ..placeholder = NA,
        ..fsn = NA,
        ..rank = NA,
        ..reg = NA,
        ..funplot = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Meta-Analysis")
            private$..text <- jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Correlation Coefficients")
            private$..plot <- jmvcore::Image$new(
                options=options,
                name="plot",
                title="Forest Plot",
                width=600,
                height=450,
                renderFun=".plot")
            private$..placeholder <- jmvcore::Preformatted$new(
                options=options,
                name="placeholder",
                title="Publication Bias Assessment")
            private$..fsn <- jmvcore::Preformatted$new(
                options=options,
                name="fsn",
                title="Fail-Safe N Analysis")
            private$..rank <- jmvcore::Preformatted$new(
                options=options,
                name="rank",
                title="Rank Correlation Test for Funnel Plot Asymmetry")
            private$..reg <- jmvcore::Preformatted$new(
                options=options,
                name="reg",
                title="Regression Test for Funnel Plot Asymmetry")
            private$..funplot <- jmvcore::Image$new(
                options=options,
                name="funplot",
                title="Funnel Plot",
                width=600,
                height=450,
                renderFun=".funplot")
            self$add(private$..text)
            self$add(private$..plot)
            self$add(private$..placeholder)
            self$add(private$..fsn)
            self$add(private$..rank)
            self$add(private$..reg)
            self$add(private$..funplot)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
MetaCorrBase <- R6::R6Class(
    "MetaCorrBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MetaModel',
                name = 'MetaCorr',
                version = c(1,0,0),
                options = options,
                results = MetaCorrResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Correlation Coefficients
#'
#' 
#' @param data .
#' @param rcor .
#' @param samplesize .
#' @param methodmetacor .
#' @param cormeasure .
#' @param fsntype .
#' @param yaxis .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$placeholder} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$fsn} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$rank} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$reg} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$funplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
MetaCorr <- function(
    data,
    rcor,
    samplesize,
    methodmetacor = "REML",
    cormeasure = "ZCOR",
    fsntype = "Rosenthal",
    yaxis = "sei") {

    options <- MetaCorrOptions$new(
        rcor = rcor,
        samplesize = samplesize,
        methodmetacor = methodmetacor,
        cormeasure = cormeasure,
        fsntype = fsntype,
        yaxis = yaxis)

    results <- MetaCorrResults$new(
        options = options)

    analysis <- MetaCorrClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
