
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
MetaCorrOptions <- R6::R6Class(
    "MetaCorrOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rcor = NULL,
            samplesize = NULL,
            slab = NULL,
            moderatorcor = NULL,
            includemods = FALSE,
            methodmetacor = "REML",
            cormeasure = "ZCOR",
            level = 95,
            addcred = FALSE,
            addfit = TRUE,
            showweights = FALSE,
            xAxisTitle = NULL,
            forestOrder = "fit",
            fsntype = "Rosenthal",
            yaxis = "sei", ...) {

            super$initialize(
                package='MetaModel',
                name='MetaCorr',
                requiresData=TRUE,
                ...)
        
            private$..rcor <- jmvcore::OptionVariable$new(
                "rcor",
                rcor,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous"))
            private$..samplesize <- jmvcore::OptionVariable$new(
                "samplesize",
                samplesize,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous"))
            private$..slab <- jmvcore::OptionVariable$new(
                "slab",
                slab)
            private$..moderatorcor <- jmvcore::OptionVariable$new(
                "moderatorcor",
                moderatorcor)
            private$..includemods <- jmvcore::OptionBool$new(
                "includemods",
                includemods,
                default=FALSE)
            private$..methodmetacor <- jmvcore::OptionList$new(
                "methodmetacor",
                methodmetacor,
                options=list(
                    "DL",
                    "HE",
                    "HS",
                    "SJ",
                    "ML",
                    "REML",
                    "EB",
                    "PM",
                    "FE"),
                default="REML")
            private$..cormeasure <- jmvcore::OptionList$new(
                "cormeasure",
                cormeasure,
                options=list(
                    "COR",
                    "UCOR",
                    "ZCOR"),
                default="ZCOR")
            private$..level <- jmvcore::OptionNumber$new(
                "level",
                level,
                min=50,
                max=99.9,
                default=95)
            private$..addcred <- jmvcore::OptionBool$new(
                "addcred",
                addcred,
                default=FALSE)
            private$..addfit <- jmvcore::OptionBool$new(
                "addfit",
                addfit,
                default=TRUE)
            private$..showweights <- jmvcore::OptionBool$new(
                "showweights",
                showweights,
                default=FALSE)
            private$..xAxisTitle <- jmvcore::OptionString$new(
                "xAxisTitle",
                xAxisTitle)
            private$..forestOrder <- jmvcore::OptionList$new(
                "forestOrder",
                forestOrder,
                options=list(
                    "obs",
                    "fit",
                    "prec",
                    "resid",
                    "abs.resid"),
                default="fit")
            private$..fsntype <- jmvcore::OptionList$new(
                "fsntype",
                fsntype,
                options=list(
                    "Rosenthal",
                    "Orwin",
                    "Rosenberg"),
                default="Rosenthal")
            private$..yaxis <- jmvcore::OptionList$new(
                "yaxis",
                yaxis,
                options=list(
                    "sei",
                    "seinv",
                    "vi",
                    "vinv",
                    "ni",
                    "ninv",
                    "sqrtni",
                    "sqrtninv",
                    "lni"),
                default="sei")
        
            self$.addOption(private$..rcor)
            self$.addOption(private$..samplesize)
            self$.addOption(private$..slab)
            self$.addOption(private$..moderatorcor)
            self$.addOption(private$..includemods)
            self$.addOption(private$..methodmetacor)
            self$.addOption(private$..cormeasure)
            self$.addOption(private$..level)
            self$.addOption(private$..addcred)
            self$.addOption(private$..addfit)
            self$.addOption(private$..showweights)
            self$.addOption(private$..xAxisTitle)
            self$.addOption(private$..forestOrder)
            self$.addOption(private$..fsntype)
            self$.addOption(private$..yaxis)
        }),
    active = list(
        rcor = function() private$..rcor$value,
        samplesize = function() private$..samplesize$value,
        slab = function() private$..slab$value,
        moderatorcor = function() private$..moderatorcor$value,
        includemods = function() private$..includemods$value,
        methodmetacor = function() private$..methodmetacor$value,
        cormeasure = function() private$..cormeasure$value,
        level = function() private$..level$value,
        addcred = function() private$..addcred$value,
        addfit = function() private$..addfit$value,
        showweights = function() private$..showweights$value,
        xAxisTitle = function() private$..xAxisTitle$value,
        forestOrder = function() private$..forestOrder$value,
        fsntype = function() private$..fsntype$value,
        yaxis = function() private$..yaxis$value),
    private = list(
        ..rcor = NA,
        ..samplesize = NA,
        ..slab = NA,
        ..moderatorcor = NA,
        ..includemods = NA,
        ..methodmetacor = NA,
        ..cormeasure = NA,
        ..level = NA,
        ..addcred = NA,
        ..addfit = NA,
        ..showweights = NA,
        ..xAxisTitle = NA,
        ..forestOrder = NA,
        ..fsntype = NA,
        ..yaxis = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
MetaCorrResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        textRICH = function() private$..textRICH,
        tableTauSqaured = function() private$..tableTauSqaured,
        tableQTest = function() private$..tableQTest,
        plot = function() private$..plot,
        placeholder = function() private$..placeholder,
        fsn = function() private$..fsn,
        rank = function() private$..rank,
        reg = function() private$..reg,
        funplot = function() private$..funplot),
    private = list(
        ..textRICH = NA,
        ..tableTauSqaured = NA,
        ..tableQTest = NA,
        ..plot = NA,
        ..placeholder = NA,
        ..fsn = NA,
        ..rank = NA,
        ..reg = NA,
        ..funplot = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Meta-Analysis")
            private$..textRICH <- jmvcore::Table$new(
                options=options,
                name="textRICH",
                title="Random-Effects Model - Correlation Coefficients",
                rows=1,
                columns=list(
                    list(`name`="Intercept", `title`="", `type`="text"),
                    list(`name`="Estimate", `type`="number"),
                    list(`name`="se", `type`="number"),
                    list(`name`="Z", `type`="number"),
                    list(`name`="p", `type`="number", `format`="zto,pvalue"),
                    list(`name`="CI", `title`="Confidence Interval", `type`="number")))
            private$..tableTauSqaured <- jmvcore::Table$new(
                options=options,
                name="tableTauSqaured",
                title="Heterogeneity Statistics",
                rows=1,
                columns=list(
                    list(`name`="tauSQRT", `title`="Tau", `type`="number", `format`="zto"),
                    list(`name`="tauSqComb", `title`="Tau\u00B2", `type`="number", `format`="zto"),
                    list(`name`="ISqu", `title`="I\u00B2", `type`="text"),
                    list(`name`="HSqu", `title`="H\u00B2", `type`="number", `format`="zto")))
            private$..tableQTest <- jmvcore::Table$new(
                options=options,
                name="tableQTest",
                title="Tests for Heterogeneity",
                rows=1,
                columns=list(
                    list(`name`="QallDF", `title`="df", `type`="integer", `format`="zto"),
                    list(`name`="Qall", `title`="Q", `type`="number", `format`="zto"),
                    list(`name`="QallPval", `title`="p", `type`="number", `format`="zto,pvalue")))
            private$..plot <- jmvcore::Image$new(
                options=options,
                name="plot",
                title="Forest Plot",
                width=600,
                height=450,
                renderFun=".plot")
            private$..placeholder <- jmvcore::Preformatted$new(
                options=options,
                name="placeholder",
                title="Publication Bias Assessment")
            private$..fsn <- jmvcore::Preformatted$new(
                options=options,
                name="fsn",
                title="Fail-Safe N Analysis")
            private$..rank <- jmvcore::Preformatted$new(
                options=options,
                name="rank",
                title="Rank Correlation Test for Funnel Plot Asymmetry")
            private$..reg <- jmvcore::Preformatted$new(
                options=options,
                name="reg",
                title="Regression Test for Funnel Plot Asymmetry")
            private$..funplot <- jmvcore::Image$new(
                options=options,
                name="funplot",
                title="Funnel Plot",
                width=600,
                height=450,
                renderFun=".funplot")
            self$add(private$..textRICH)
            self$add(private$..tableTauSqaured)
            self$add(private$..tableQTest)
            self$add(private$..plot)
            self$add(private$..placeholder)
            self$add(private$..fsn)
            self$add(private$..rank)
            self$add(private$..reg)
            self$add(private$..funplot)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
MetaCorrBase <- R6::R6Class(
    "MetaCorrBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MetaModel',
                name = 'MetaCorr',
                version = c(1,0,0),
                options = options,
                results = MetaCorrResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Correlation Coefficients
#'
#' 
#' @param data .
#' @param rcor .
#' @param samplesize .
#' @param slab .
#' @param moderatorcor .
#' @param includemods .
#' @param methodmetacor .
#' @param cormeasure .
#' @param level .
#' @param addcred .
#' @param addfit .
#' @param showweights .
#' @param xAxisTitle .
#' @param forestOrder .
#' @param fsntype .
#' @param yaxis .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$textRICH} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tableTauSqaured} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tableQTest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$placeholder} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$fsn} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$rank} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$reg} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$funplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$textRICH$asDF}
#'
#' \code{as.data.frame(results$textRICH)}
#'
#' @export
MetaCorr <- function(
    data,
    rcor,
    samplesize,
    slab,
    moderatorcor,
    includemods = FALSE,
    methodmetacor = "REML",
    cormeasure = "ZCOR",
    level = 95,
    addcred = FALSE,
    addfit = TRUE,
    showweights = FALSE,
    xAxisTitle,
    forestOrder = "fit",
    fsntype = "Rosenthal",
    yaxis = "sei") {

    options <- MetaCorrOptions$new(
        rcor = rcor,
        samplesize = samplesize,
        slab = slab,
        moderatorcor = moderatorcor,
        includemods = includemods,
        methodmetacor = methodmetacor,
        cormeasure = cormeasure,
        level = level,
        addcred = addcred,
        addfit = addfit,
        showweights = showweights,
        xAxisTitle = xAxisTitle,
        forestOrder = forestOrder,
        fsntype = fsntype,
        yaxis = yaxis)

    results <- MetaCorrResults$new(
        options = options)

    analysis <- MetaCorrClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
