
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
metamdmsOptions <- R6::R6Class(
    "metamdmsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            N1 = NULL,
            M1 = NULL,
            SD1 = NULL,
            N2 = NULL,
            M2 = NULL,
            SD2 = NULL,
            methodmetamdms = "REML",
            mdmsmeasure = "SMD",
            fsntype = "Rosenthal",
            yaxis = "sei", ...) {

            super$initialize(
                package='MetaModel',
                name='metamdms',
                requiresData=TRUE,
                ...)
        
            private$..N1 <- jmvcore::OptionVariable$new(
                "N1",
                N1)
            private$..M1 <- jmvcore::OptionVariable$new(
                "M1",
                M1)
            private$..SD1 <- jmvcore::OptionVariable$new(
                "SD1",
                SD1)
            private$..N2 <- jmvcore::OptionVariable$new(
                "N2",
                N2)
            private$..M2 <- jmvcore::OptionVariable$new(
                "M2",
                M2)
            private$..SD2 <- jmvcore::OptionVariable$new(
                "SD2",
                SD2)
            private$..methodmetamdms <- jmvcore::OptionList$new(
                "methodmetamdms",
                methodmetamdms,
                options=list(
                    "DL",
                    "HE",
                    "HS",
                    "SJ",
                    "ML",
                    "REML",
                    "EB",
                    "FE"),
                default="REML")
            private$..mdmsmeasure <- jmvcore::OptionList$new(
                "mdmsmeasure",
                mdmsmeasure,
                options=list(
                    "MD",
                    "SMD",
                    "SMDH",
                    "ROM"),
                default="SMD")
            private$..fsntype <- jmvcore::OptionList$new(
                "fsntype",
                fsntype,
                options=list(
                    "Rosenthal",
                    "Orwin",
                    "Rosenberg"),
                default="Rosenthal")
            private$..yaxis <- jmvcore::OptionList$new(
                "yaxis",
                yaxis,
                options=list(
                    "sei",
                    "seinv",
                    "vi",
                    "vinv",
                    "ni",
                    "ninv",
                    "sqrtni",
                    "sqrtninv",
                    "lni"),
                default="sei")
        
            self$.addOption(private$..N1)
            self$.addOption(private$..M1)
            self$.addOption(private$..SD1)
            self$.addOption(private$..N2)
            self$.addOption(private$..M2)
            self$.addOption(private$..SD2)
            self$.addOption(private$..methodmetamdms)
            self$.addOption(private$..mdmsmeasure)
            self$.addOption(private$..fsntype)
            self$.addOption(private$..yaxis)
        }),
    active = list(
        N1 = function() private$..N1$value,
        M1 = function() private$..M1$value,
        SD1 = function() private$..SD1$value,
        N2 = function() private$..N2$value,
        M2 = function() private$..M2$value,
        SD2 = function() private$..SD2$value,
        methodmetamdms = function() private$..methodmetamdms$value,
        mdmsmeasure = function() private$..mdmsmeasure$value,
        fsntype = function() private$..fsntype$value,
        yaxis = function() private$..yaxis$value),
    private = list(
        ..N1 = NA,
        ..M1 = NA,
        ..SD1 = NA,
        ..N2 = NA,
        ..M2 = NA,
        ..SD2 = NA,
        ..methodmetamdms = NA,
        ..mdmsmeasure = NA,
        ..fsntype = NA,
        ..yaxis = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
metamdmsResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$..text,
        plot = function() private$..plot,
        placeholder = function() private$..placeholder,
        fsn = function() private$..fsn,
        rank = function() private$..rank,
        reg = function() private$..reg,
        funplot = function() private$..funplot),
    private = list(
        ..text = NA,
        ..plot = NA,
        ..placeholder = NA,
        ..fsn = NA,
        ..rank = NA,
        ..reg = NA,
        ..funplot = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Meta-Analysis")
            private$..text <- jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Mean Differences")
            private$..plot <- jmvcore::Image$new(
                options=options,
                name="plot",
                title="Forest Plot",
                width=600,
                height=450,
                renderFun=".plot")
            private$..placeholder <- jmvcore::Preformatted$new(
                options=options,
                name="placeholder",
                title="Publication Bias Assessment")
            private$..fsn <- jmvcore::Preformatted$new(
                options=options,
                name="fsn",
                title="Fail-Safe N Analysis")
            private$..rank <- jmvcore::Preformatted$new(
                options=options,
                name="rank",
                title="Rank Correlation Test for Funnel Plot Asymmetry")
            private$..reg <- jmvcore::Preformatted$new(
                options=options,
                name="reg",
                title="Regression Test for Funnel Plot Asymmetry")
            private$..funplot <- jmvcore::Image$new(
                options=options,
                name="funplot",
                title="Funnel Plot",
                width=600,
                height=450,
                renderFun=".funplot")
            self$add(private$..text)
            self$add(private$..plot)
            self$add(private$..placeholder)
            self$add(private$..fsn)
            self$add(private$..rank)
            self$add(private$..reg)
            self$add(private$..funplot)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
metamdmsBase <- R6::R6Class(
    "metamdmsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MetaModel',
                name = 'metamdms',
                version = c(1,0,0),
                options = options,
                results = metamdmsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Mean Differences (n, M, SD)
#'
#' 
#' @param data .
#' @param N1 .
#' @param M1 .
#' @param SD1 .
#' @param N2 .
#' @param M2 .
#' @param SD2 .
#' @param methodmetamdms .
#' @param mdmsmeasure .
#' @param fsntype .
#' @param yaxis .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$placeholder} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$fsn} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$rank} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$reg} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$funplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
metamdms <- function(
    data,
    N1,
    M1,
    SD1,
    N2,
    M2,
    SD2,
    methodmetamdms = "REML",
    mdmsmeasure = "SMD",
    fsntype = "Rosenthal",
    yaxis = "sei") {

    options <- metamdmsOptions$new(
        N1 = N1,
        M1 = M1,
        SD1 = SD1,
        N2 = N2,
        M2 = M2,
        SD2 = SD2,
        methodmetamdms = methodmetamdms,
        mdmsmeasure = mdmsmeasure,
        fsntype = fsntype,
        yaxis = yaxis)

    results <- metamdmsResults$new(
        options = options)

    analysis <- metamdmsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
