
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
PubBiasOptions <- R6::R6Class(
    "PubBiasOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            yi = NULL,
            vi = NULL,
            fsntype = "Rosenthal", ...) {

            super$initialize(
                package='MetaModel',
                name='PubBias',
                requiresData=TRUE,
                ...)
        
            private$..yi <- jmvcore::OptionVariable$new(
                "yi",
                yi)
            private$..vi <- jmvcore::OptionVariable$new(
                "vi",
                vi)
            private$..fsntype <- jmvcore::OptionList$new(
                "fsntype",
                fsntype,
                options=list(
                    "Rosenthal",
                    "Orwin",
                    "Rosenberg"),
                default="Rosenthal")
        
            self$.addOption(private$..yi)
            self$.addOption(private$..vi)
            self$.addOption(private$..fsntype)
        }),
    active = list(
        yi = function() private$..yi$value,
        vi = function() private$..vi$value,
        fsntype = function() private$..fsntype$value),
    private = list(
        ..yi = NA,
        ..vi = NA,
        ..fsntype = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
PubBiasResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        fsn = function() private$..fsn,
        rank = function() private$..rank,
        reg = function() private$..reg),
    private = list(
        ..fsn = NA,
        ..rank = NA,
        ..reg = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Publication Bias")
            private$..fsn <- jmvcore::Preformatted$new(
                options=options,
                name="fsn",
                title="Fail-Safe N Analysis")
            private$..rank <- jmvcore::Preformatted$new(
                options=options,
                name="rank",
                title="Rank Correlation Test for Funnel Plot Asymmetry")
            private$..reg <- jmvcore::Preformatted$new(
                options=options,
                name="reg",
                title="Regression Test for Funnel Plot Asymmetry")
            self$add(private$..fsn)
            self$add(private$..rank)
            self$add(private$..reg)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
PubBiasBase <- R6::R6Class(
    "PubBiasBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MetaModel',
                name = 'PubBias',
                version = c(1,0,0),
                options = options,
                results = PubBiasResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Publication Bias
#'
#' 
#' @param data .
#' @param yi .
#' @param vi .
#' @param fsntype .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$fsn} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$rank} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$reg} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
PubBias <- function(
    data,
    yi,
    vi,
    fsntype = "Rosenthal") {

    options <- PubBiasOptions$new(
        yi = yi,
        vi = vi,
        fsntype = fsntype)

    results <- PubBiasResults$new(
        options = options)

    analysis <- PubBiasClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
